language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: g++-5
      env: COMPILER=g++ -std=c++11

script:
  - cd lab-01
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..

