language: cpp
sudo: true

notifications:
  email: false

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cd lab-08
  - mkdir build && cd build
  - cmake .. && make
  - ./executable
  - cd ../..
  
  - cd lab-01
  - mkdir build && cd build
  - cmake .. && make
  - ./executable
  - cd ../..
  
  - cd lab-02
  - mkdir build && cd build
  - cmake .. && make
  - ./executable
  - cd ../sorting
  - mkdir build && cd build
  - cmake .. && make
  - ./executable
  - cd ../../..

  - cd lab-03
  - mkdir build && cd build
  - cmake .. && make
  - ./solution_equation
  - ./memory_leak
  - ./raii
  - cd ../..
